export const Path = {
  Index: '/',
  Login: '/login',
  Service: '/service',
  ServiceType: '/service-type',
  Combo: '/combo',
  Course: '/course',
  ServiceDetail: '/service-detail/',
  Staff: '/staff',
  Customer: '/customer',
  Branch: '/branch',
  NOT_FOUND: '/404',
  FORBIDDEN: '/403',
  WorkSchedule: '/work-schedule',
  LeaveSchedule: '/leave-schedule',
  TourSchedule: '/tour-schedule',
  CourseSchedule: '/course-schedule',
  PayBill: '/pay-bill',
  Salary: '/sarary'
};
