@url=http://localhost:8888/api/v1/branches

### CREATE
POST {{ url }}
Content-Type: application/json

{
	"name": "HTT SPA",
	"code": "cn3",
	"address": "3/2, Ninh Kiều, Cần Thơ",
	"desc": "Chi nhánh 2",
	"capacity": 5,
	"manager": "64a6dc237004fb28bcd6f96c",
	"startTime": "09:00",
	"endTime": "20:00"
}

### GET
GET {{url}}

### GET ID
GET {{url}}/650007e9c31b396b0f6ef13d
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NTc5NDYxOSwiZXhwIjoxNjk2NjU4NjE5fQ.AoEI3U8AMO80EG02jtgw8fr4F_j_tzMSk1XUOPEWzGY

### Update
PATCH {{url}}/64e9706d1c8a7891e629d7f1
Content-Type: application/json

{
  "endTime": "10:00"
}




