@url=http://localhost:8888/api/v1/combos

### CREATE
POST {{url}}
Content-Type: application/json
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NjUwNjk3MiwiZXhwIjoxNjk3MzcwOTcyfQ.vPawbwawnOc0DNEXAYkTceNo-czbXNUW5ILoMDfo5Gk

{
  "code": "CB001",
  "name": "Massage body",
  "price": 249000,
  "duration": 90,
  "services": [],
  "desc": "Massage body thư giãn, dưỡng sinh và trị liệu"
}

### Update
PATCH {{url}}/6528b5b4d4eafe8ea02623df
Content-Type: application/json
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NjUwNjk3MiwiZXhwIjoxNjk3MzcwOTcyfQ.vPawbwawnOc0DNEXAYkTceNo-czbXNUW5ILoMDfo5Gk

{
  "code": "CB001",
  "name": "Combo body gội",
  "price": 249000,
  "duration": 90,
  "services": [],
  "desc": "Combo body gội thư giãn, dưỡng sinh và trị liệu"
}

### GET
GET {{url}}
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NjUwNjk3MiwiZXhwIjoxNjk3MzcwOTcyfQ.vPawbwawnOc0DNEXAYkTceNo-czbXNUW5ILoMDfo5Gk

### GET ID
GET {{url}}/652944bc90a19111a4a2a556
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY
