@url=http://localhost:8888/api/v1/courses

### CREATE
POST {{url}}
Content-Type: application/json
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NjUwNjk3MiwiZXhwIjoxNjk3MzcwOTcyfQ.vPawbwawnOc0DNEXAYkTceNo-czbXNUW5ILoMDfo5Gk

{
  "code": "LT001",
  "name": "Gội đầu thư giãn gói 1",
  "package_details": [],
  "imgs": [],
  "duration": 30,
  "consultingCommission": 0,
  "technicianCommission": 0,
  "desc": "",
  "services": []
}

### Update
PATCH {{url}}/652a9c3c0282e4377377d6d0
Content-Type: application/json
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NjUwNjk3MiwiZXhwIjoxNjk3MzcwOTcyfQ.vPawbwawnOc0DNEXAYkTceNo-czbXNUW5ILoMDfo5Gk

{
  "code": "LT001",
  "name": "Gội đầu thư giãn gói 1",
  "package_details": [
    {
      "times": 5,
    "price": 529000
    },
    {
      "times": 5,
    "price": 529000
    }
  ],
  "imgs": [],
  "duration": 30,
  "consultingCommission": 0,
  "technicianCommission": 0,
  "desc": "",
  "services": []
}

### GET
GET {{url}}
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY

### GET ID
GET {{url}}/652a9c3c0282e4377377d6d0
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY
