@url=http://localhost:8888/api/v1/customers

### CREATE
POST {{ url }}
Content-Type: application/json

{
  "code": "KH00000002",
  "fullname": "Nguyễn Văn Phúc",
  "phone": "0907811367",
  "password": "",
  "email": "",
  "address": "Hậu Giang",
  "gender": "nam",
  "birthday": "1976-12-12T00:00:00.000Z",
  "customerLevel": 1,
  "score": 0
}


### GET
GET {{url}}
# x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY


### GET ID
GET {{url}}/65475bae33e9bd33a73275c8
# x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDZkMDM4Y2MzMTU0NzA1Njc3NzcxOCIsInJvbGUiOiJzdGFmZiIsImlhdCI6MTY5NjIyNzc5OCwiZXhwIjoxNjk3MDkxNzk4fQ.Sy1qvSsRtqdXfSyPzUwp8rjvMkaqmhXErgWGKv9chx0


### Update
PATCH {{url}}/65475bae33e9bd33a73275c8
Content-Type: application/json

{
  "code": "KH00000002",
  "fullname": "Nguyễn Văn Phúc",
  "phone": "0907811367",
  "password": "Nvp7676",
  "email": "phuc@gmail.com",
  "address": "Hậu Giang",
  "gender": "nam",
  "birthday": "1976-12-12T00:00:00.000Z",
  "customerLevel": 1,
  "score": 0
}
### Login
POST {{ url }}/login
Content-Type: application/json

{
	"username": "qlcn0101",
	"password": "Hao291001"
}

### Logout
GET {{ url }}/logout



