@url=http://localhost:8888/api/v1/customers

### CREATE
POST {{ url }}
Content-Type: application/json

{
  "fullname": "Huynh Thanh Thuong 1",
  "phone": "123456789",
  "email": "john.doe@example.com",
  "address": "123 Main St",
  "password": "password123",

}


### GET
GET {{url}}
# x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY


### GET ID
GET {{url}}/651588404eb4c2adc3f3b529
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDZkMDM4Y2MzMTU0NzA1Njc3NzcxOCIsInJvbGUiOiJzdGFmZiIsImlhdCI6MTY5NjIyNzc5OCwiZXhwIjoxNjk3MDkxNzk4fQ.Sy1qvSsRtqdXfSyPzUwp8rjvMkaqmhXErgWGKv9chx0


### Update
PATCH {{url}}/64ed80658d9907fd5dedd129
Content-Type: application/json

{

}

### Login
POST {{ url }}/login
Content-Type: application/json

{
	"username": "qlcn0101",
	"password": "Hao291001"
}

### Logout
GET {{ url }}/logout



