@url=http://localhost:8888/api/v1/owners

### CREATE
POST {{ url }}
Content-Type: application/json

{
	"fullname": "Nguyễn Văn Hào",
"username": "zvhao",
"phone": "0938744376",
"email": "hao@gmail.com",
"shop_name": "ZVHAO SPA",
"password": "Hao291001",
"roles": ["64f5c5d02c268c9c00c1fe27", "64f5c8432c268c9c00c1fe2b", "64f5c8f62c268c9c00c1fe2f"]
}

### GET
GET {{url}}

### GET ID
GET {{url}}/64a6abb778a2f2d5d44683ce

### Update
PATCH {{url}}/64a6abdab147e8ab6a84a2ac
Content-Type: application/json

{
  "fullname": "Nguyễn Văn Hào",
	"shop_name": "ZVH Spa",
	"email": "nguyenvanhao29102001@gmail.com"
}

### Login
POST {{ url }}/login
Content-Type: application/json

{
	"username": "zvhao1",
	"password": "Hao291001"
}

### Logout
GET {{ url }}/logout



