@url=http://localhost:8888/api/v1/permissions

### CREATE
POST {{url}}
Content-Type: application/json

{
  "name": "staff view",
  "desc": "Xem nhân viên",
  "alias": "staff.view"
}







### Update
PATCH {{url}}/64a62e740d8f3b349377957a
Content-Type: application/json

{
  "name": "Product add",
  "desc": "Thêm ",
  "alias": "product.add"
}

### GET
GET {{url}}
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY


### GET ID
GET {{url}}/64a62e740d8f3b349377957a