@url=http://localhost:8888/api/v1/permissions

### CREATE
POST {{url}}
Content-Type: application/json

{
  "name": "booking update",
  "desc": "cập nhật lịch hẹn",
  "alias": "booking.update"
}







### Update
PATCH {{url}}/64a62e740d8f3b349377957a
Content-Type: application/json

{
  "name": "Product add",
  "desc": "Thêm ",
  "alias": "product.add"
}

### GET
GET {{url}}


### GET ID
GET {{url}}/64a62e740d8f3b349377957a