@url=http://localhost:8888/api/v1/roles

### CREATE
POST {{url}}
Content-Type: application/json

{
  "name": "technicians",
  "desc": "Kỹ thuật viên",
  "permissions": ["653bca92ec8ec92cb6207084", "653bcb04ec8ec92cb620ab73"]
}

### Update
PATCH {{url}}/653bcb13ec8ec92cb620ab76
Content-Type: application/json
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY

{
  "name": "staff",
  "desc": "Nhân viên thường",
  "permissions": ["653bca92ec8ec92cb6207084", "653bcb04ec8ec92cb620ab73"]
}

### GET
GET {{url}}
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY


### GET ID
GET {{url}}/651582fb9dce25997d637c13
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY
