@url=http://localhost:8888/api/v1/staffs

### CREATE
POST {{ url }}
Content-Type: application/json

{
  "fullname": "Huynh Thanh Thuong 1",
  "username": "qlcn0102",
  "phone": "123456789",
  "email": "john.doe@example.com",
  "address": "123 Main St",
  "numPaidLeave": 2,
  "basicSalary": 5000000,
  "position": "Manager",
  "password": "password123",
  "consultingCommission": 0.1,
  "serviceCommission": 0.1,
  "allowances": [
    {
      "name": "Allowance 1",
      "allowance": 100000
    },
    {
      "name": "Allowance 2",
      "allowance": 200000
    }
  ],
  "workTime": [
    {
      "startDate": "2023-09-16T13:03:00.000Z",
      "weekSchedule": [
        {
          "day": "Monday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Tuesday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Wednesday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Thursday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Friday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Saturday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Sunday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        }
      ]
    }
  ],
  "role": "65066da369700b9f042aa256",
  "branch": "650007e9c31b396b0f6ef13d"
}


### GET
GET {{url}}
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5NzUxMTA0MCwiZXhwIjoxNjk4Mzc1MDQwfQ.3NVAvsh29IyIQMz-E5VseBRDcDj5xLdVZN6Y43WpFiY


### GET ID
GET {{url}}/651588404eb4c2adc3f3b529
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDZkMDM4Y2MzMTU0NzA1Njc3NzcxOCIsInJvbGUiOiJzdGFmZiIsImlhdCI6MTY5NjIyNzc5OCwiZXhwIjoxNjk3MDkxNzk4fQ.Sy1qvSsRtqdXfSyPzUwp8rjvMkaqmhXErgWGKv9chx0


### Update
PATCH {{url}}/64ed80658d9907fd5dedd129
Content-Type: application/json

{
  "fullname": "Huynh Thanh Thuong",
  "username": "qlcn04",
  "phone": "0938744376",
  "email": "thuong@gmail.com",
  "address": "Nguyen De",
  "numPaidLeave": 2,
  "basicSalary": 4000000,
  "position": "Manager",
  "password": "password123",
  "consultingCommission": 0.1,
  "serviceCommission": 0.1,
  "allowances": [
    {
      "nameAllowance1": "phụ cấp tiền xăng",
      "moneyAllowance1": 500000,
    },
    {
      "nameAllowance2": "phụ cấp tiền ăn",
      "moneyAllowance2": 500000,
    }
  ],
  "workTime": [
    {
      "startDate": "2023-08-30",
      "weekSchedule": [
        {
          "day": "Monday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Tuesday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Wednesday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Thursday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Friday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Saturday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        },
        {
          "day": "Sunday",
          "startTime": "2023-09-16T13:03:00.000Z",
          "endTime": "2023-09-16T13:03:00.000Z"
        }
      ]
    }
  ],
  "roles": ["64a639e9070a377cbf828939", "64a6b717d2cb99cfbec2bf78"],
  "branches": ["64e5d24baea54b37f51fbeb8"]
}

### Login
POST {{ url }}/login
Content-Type: application/json

{
	"username": "qlcn0101",
	"password": "Hao291001"
}

### Logout
GET {{ url }}/logout



