@url=http://localhost:8888/api/v1/staffDayOffs

### CREATE
POST {{ url }}
Content-Type: application/json
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5ODU5MjMyNCwiZXhwIjoxNzAzNzc2MzI0fQ.5nqsUxSDwTEe6SAS12WQako2TmCGoPy1_0jc5i5dRIA

{
	"branch": "650007e9c31b396b0f6ef13d",
	"staff": "65410252498c0c02e2c6ef63",
	"dayOff": "2023-11-11T00:00:00.000Z",
	"reason": "Bệnh",
	"status": 1
}

### GET
GET {{url}}
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5ODU5MjMyNCwiZXhwIjoxNzAzNzc2MzI0fQ.5nqsUxSDwTEe6SAS12WQako2TmCGoPy1_0jc5i5dRIA



### GET ID
GET {{url}}/653b77dd6a2a75d71715c0c3

### Update
PATCH {{url}}/653e76f5cb224e8a9c00eacb
Content-Type: application/json
x-client-id:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjk0MjI5N2RhNDQzMjEzZmE2NTAwOCIsInJvbGUiOiJvd25lciIsImlhdCI6MTY5ODU5MjMyNCwiZXhwIjoxNzAzNzc2MzI0fQ.5nqsUxSDwTEe6SAS12WQako2TmCGoPy1_0jc5i5dRIA

{
	"status": 1
}





